# TODO: Remove when https://github.com/travis-ci/travis-ci/issues/1379
# is resolved.
before_install:
        - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test"
        - "sudo apt-get -qq update"
        - "sudo apt-get -qq install g++-4.9"

language: c
compiler:
        - gcc
script:
        - "gcc -v"
        - "cd src; make test"
