language: c

# TODO: Remove when https://github.com/travis-ci/travis-ci/issues/1379
# is resolved.
install:
        - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test"
        - "sudo apt-get -qq update"
        - "sudo apt-get -qq install g++-4.7"

script: cd src; make test
compiler:
        - gcc
